### ISSUE TITLE
Allow the list of allowed extensions for finding schema files to be provided as CLI option

### ISSUE THREAD

**Issue by adamcunnington-mlg** [coveooss/json-schema-for-humans#117]
Currently, I cannot use this package because the expected extensions for schema files is hardcoded.

I am using Google Cloud deployment manager to define my templates and it requires that I give the files a .schema extension. This is incompatible with json-schema-for-humans - please can you allow the extension to be provided as a CLI option?

**Comment by adamcunnington-mlg** [comment]
Or a faster short term solution... can we just change the glob patterns [here](https://github.com/coveooss/json-schema-for-humans/blob/master/json_schema_for_humans/schema/schema_importer.py#L18) to have a trailing `*`, e.g.:
```python
schema_file_paths += [schema_path for schema_path in schema_file_or_dir.glob("**/*.json*")]
schema_file_paths += [schema_path for schema_path in schema_file_or_dir.glob("**/*.ya?ml*")]
```

**Comment by dblanchette** [comment]
Sure, I'll make it configurable

**Comment by dblanchette** [comment]
@adamcunnington-mlg How about naking it so that the provided path can be the following:
- A path to a single JSON file
- A path to a directory (in which case all .json, .yaml, and .yml files are used there)
- A glob pattern

i.e.:
```    if schema_file_or_dir.is_file():
        schema_file_paths.append(schema_file_or_dir)
    elif schema_file_or_dir.is_dir():
        schema_file_paths += [schema_path for schema_path in schema_file_or_dir.glob("**/*.json")]
        schema_file_paths += [schema_path for schema_path in schema_file_or_dir.glob("**/*.ya?ml")]
    else:
        schema_file_paths += [schema_path for schema_path in Path.cwd().glob(str(schema_file_or_dir))]

    return schema_file_paths
```

This would not change the existing behaviour and would be simple to use (if a little surprising)

**Comment by adamcunnington-mlg** [comment]
@dblanchette thanks. Also I think your current glob pattern implementation is too restrictive. It's quite common to have paths like this:
.yaml.jinja
.yaml.jinja.schema

**/*.yaml* (as I suggested above) won't work on its own. It would need a * before the .yaml too. So when you make this configurable, perhaps you make the entire file extension path configurable.

EDIT: I think your suggestion is spot on - allow user to provide a glob and that way, it will be maximally flexible.

**Comment by adamcunnington-mlg** [comment]
@dblanchette by the way, if you are about to raise a PR, can you also a fix a really tiny but irritating rendering issue with the HTML footer?

I can't work out what is wrong with the [code](https://github.com/coveooss/json-schema-for-humans/blob/master/json_schema_for_humans/templates/js/base.html#L35) but for some reason, there's no space between the "json-schema-for-humans" link and the word "on" in the footer.

![image](https://user-images.githubusercontent.com/93528462/141317798-4fd7ead8-7894-43f5-ac9b-cc9e96f3bbab.png)

**Comment by adamcunnington-mlg** [comment]
@dblanchette finally, and let me know if you want to consider this a separate feature request, but it is connected - when you glob for schema files, i think it's common that you want the output to match the same directory structure.

E.g. if I find foo/bar.schema and foo/baz/xyz.schema and I provide an output path of docs/, I want the output structure to match; e.g. /docs/bar.html and /docs/xyz.html

At the moment, because I have identically named files but in different directories, json-schema-for-humans is overriding the output html file and I am forced to either rename my files (not possible because of a separate constraint) or run the tool multiple times with different paths (my current reluctant workaround).

Let me know your thoughts. I would think this would just be another option you could provide in config-file, "output_dir_mirror_structure"

**Comment by dblanchette** [comment]
Version 0.39 (just released) contains the change allowing to pass a glob pattern as input.

Working on the rest

**Comment by dblanchette** [comment]
For the missing space in the footer:

Normally, `-%}` in jinja should remove the whitespace after it, so the code should not work. Weirdly it does leave the space when I run it. Anyway, I removed the `-` in version 0.39.1. 

Let me know if that fixes it for you.

**Comment by dblanchette** [comment]
For the mirroring, I created #118. It's something I did feel bad not doing in my last refactor, but I don't have time for it right now. Let me know if you want to start a PR :)
