### ISSUE TITLE
Support for later PyYAML

### ISSUE THREAD

**Issue by fabaff** [coveooss/json-schema-for-humans#127]
The current constraint [`PyYAML = "^5.4.1"`](https://github.com/coveooss/json-schema-for-humans/blob/main/pyproject.toml#L34) doesn't allow to use the latest PyYAML releases.

Would be nice if PyYAML > 6 could be supported. Especially useful for distribution which are shipping `json-schema-for-humans` as package and people who are using it in a `venv` with other modules.

**Comment by dblanchette** [comment]
Should be all good in version 0.40
