### ISSUE TITLE
Option to output property format 

### ISSUE THREAD

**Issue by xsampedro** [coveooss/json-schema-for-humans#130]
Given:

`  "EventTimestamp": {
      "type": "string",
      "format": "date-time"
    },`

It would be useful to be able to output the format next to the type.

**Comment by dblanchette** [comment]
Hi @xsampedro , I'm not sure I understand the request, could you give more info?

**Comment by xsampedro** [comment]
HI @dblanchette, I'm sorry for not being clear, and thanks for coming back to me. :)

I would like to have the property **format**, `date-time` in this example, in the HTML/markdown JSON Schema for Humans produces.

Maybe that is already possible?

**Comment by Dzordzu** [comment]
Created a PR. Below you can see effects

![image](https://user-images.githubusercontent.com/17514622/168064722-c6ae1ee0-aeb8-4cbc-ad8a-7aad860007e7.png)

**Comment by Dzordzu** [comment]
@dblanchette Also the readme should be fixed https://github.com/coveooss/json-schema-for-humans/blob/main/README.md?plain=1#L137-L138
