### ISSUE TITLE
Extended schemas not displaying correctly

### ISSUE THREAD

**Issue by Azureuse** [coveooss/json-schema-for-humans#131]
Firstly, I love this tool. Creates such great documentation with so little effort. 

I think I've stumbled onto a slight bug / edge case where the output isn't what I would expect. I have a situation where I have a number of variants on a type of object. I want to define the schema for the common parts once and then reference that, only defining unique behaviour within each object.

The json-schema docs suggest I should be able to do that using `allOf` as shown here: https://json-schema.org/understanding-json-schema/reference/object.html#unevaluated-properties
```
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  ],

  "properties": {
    "type": { "enum": ["residential", "business"] }
  },
  "required": ["type"],
  "unevaluatedProperties": false
}
```

Here is an example I have put together using the above method of schema extension that shows the output produced (using the js template):
```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/address_book.schema.json",
  "title": "Address Book",
  "description": "Addresses from my book",
  "type": "object",
  "properties": {
    "address_flat": {
      "type": "object",
      "description": "The desired output, but I don't want to have to re-define the common properties here.",
      "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" },
        "type": { "enum": ["residential", "business"] },
        "parking": { "type": "boolean" }
      },
      "required": ["street_address", "city", "state", "type"],
      "unevaluatedProperties": false
    },
    "address_allOf": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "street_address": { "type": "string" },
            "city": { "type": "string" },
            "state": { "type": "string" }
          },
          "required": ["street_address", "city", "state"]
        }
      ],
      "description": "The output produced when using `allOf` for schema extension. The `type` and `parking` properties are missing.",
      "properties": {
        "type": { "enum": ["residential", "business"] },
        "parking": { "type": "boolean" }
      },
      "required": ["type"],
      "unevaluatedProperties": false
    },
    "address_allOf_ref": {
      "allOf": [{ "$ref": "#/$defs/commonProps" }],
      "description": "The output produced when using `allOf`  and `$ref` for schema extension. The `type` and `parking` properties are missing.",
      "properties": {
        "type": { "enum": ["residential", "business"] },
        "parking": { "type": "boolean" }
      },
      "required": ["type"],
      "unevaluatedProperties": false
    }
  },
  "$defs": {
    "commonProps": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  }
}
```

![image](https://user-images.githubusercontent.com/4603846/158152774-dfb409e9-4db6-42c8-b256-e75c4b115bf1.png)

![image](https://user-images.githubusercontent.com/4603846/158152840-9deaa7ea-aeaa-450a-a6e3-a04f75ce3712.png)

![image](https://user-images.githubusercontent.com/4603846/158152894-09da5f6b-5511-405d-a54d-4bb4c65f8424.png)

Is there a way of restructuring the json to produce the output I want using json-schema-for-humans? Or is this a bug to be fixed / feature to be added?

Hopefully the above is clear!

**Comment by dblanchette** [comment]
Hi! Thanks for the detailed issue.

`unevaludatedProperties` is new to draft 2019-09 which was not out when I started this library.

To be fully transparent, I don't know when I'll have the time and motivation to work on this as I have to do it on evenings and weekends.

I'm always willing to accept PRs.

**Comment by moulinfr** [comment]
Hi,

As @Azureuse I just want to mention again that this tool is really a great piece of work; I love it! Many thanks @dblanchette for your dedication.

Similarly, I would like to generate the documentation of a JSON schema with an extension of an object **without** _unevaludatedProperties_ ; basically:

```
{
  "definitions": {
    "description": "this is an extended object",
    "base": {
      "description": "this is the base object",
      "type": "object",
      "properties": {
        "foo": {"type": "string"},
       "bar": {"type": "string"}
      },
      "required": ["foo", "bar"]
    }},
  "allOf": [{"$ref": "#/definitions/base"}],
  "properties": {
    "baz": {"type": "string"}},
  "required": ["baz"]}
```

The output documentation is:
![image](https://user-images.githubusercontent.com/32124778/205374072-4f8c6d97-9643-49c5-87a3-800452c4c769.png)

I would expect the _baz_ property to be documented, but it's not. Do you think there is a better way to write the schema or a chance to modify the tool to do it?

Thank you all for your suggestions

**Comment by moulinfr** [comment]
I do confirm the @pspot2's comment in #171:

> Note: the document is rendered correctly if the contents of schema_test2.json is provided directly inside the allOf block instead of being referenced.
