### ISSUE TITLE
Restrict "Additional Properties" markdown field to object schemas

### ISSUE THREAD

**Issue by dexterduck** [coveooss/json-schema-for-humans#132]
Currently the default markdown templates show the "Additional Properties" field for every schema/subschema, even though `additionalProperties` is only valid for `object` schemas.

Since this adds a fair amount of clutter to generated files, it would be great if it were possible to make displaying the field conditional on `object` being a valid type for the schema.

**Comment by dblanchette** [comment]
Hi @dexterduck, sorry for taking so long to reply.

Currently `No Additional Properties` is displayed when the keyword `properties` or `patternProperties` is used and `additionalProperties` is false (it must be set explicitely to false)

Or as code:
```python
@property
def explicit_no_additional_properties(self) -> bool:
    """Return True if additionalProperties is set and false (to differentiate from not set)"""
    return bool(
        (self.properties or self.pattern_properties)
        and self.no_additional_properties
        and not self.additional_properties
    )
```

```
{%- if schema.explicit_no_additional_properties -%}
    {{ " " }}<span class="badge badge-info no-additional">No Additional Properties</span>
{%- endif -%}
```

Do you have a schema example that exhibits the unwanted behavior?

Maybe a switch to disable the `No Additional Properties` badge altogether would be the best in your situation?

**Comment by dexterduck** [comment]
Hey, thanks for the reply! 

I'm using version `0.40.5` with Python `3.9.10`.

If I process the following schema:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "Test.json",
    "title": "Test",
    "type": "integer"
}
```

Using this script:
```python
from pathlib import Path
from json_schema_for_humans.generate import (
    GenerationConfiguration,
    generate_from_filename,
)

in_path = Path("path/to/schema/")
out_path = Path("path/to/markdown/")
config = GenerationConfiguration(
    template_name="md_nested",
    show_toc=False,
    template_md_options=dict(badge_as_image=True)
)

generate_from_filename(in_path, out_path, config=config)
```

I get this output:

---

# Test

**Title:** Test

| Type                      | `integer`                                                                                                           |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------- |
| **Additional properties** | [![badge](https://img.shields.io/badge/Any+type-allowed-green)](# "Additional Properties of any type are allowed.") |
|                           |                                                                                                                     |

----------------------------------------------------------------------------------------------------------------------------
Generated using [json-schema-for-humans](https://github.com/coveooss/json-schema-for-humans) on 2022-05-17 at 13:44:25 -0400
