### ISSUE TITLE
Documentation for deprecation is incorrect

### ISSUE THREAD

**Issue by GlenNicholls** [coveooss/json-schema-for-humans#138]
Based on the [docs](https://coveooss.github.io/json-schema-for-humans/#/Examples?id=deprecation-notice), it states that if a description **contains** the string `[Deprecated`, it will add a red badge (assuming the correct flag is enabled.) This is actually incorrect, after playing around with it for a bit, I found it only works when the description starts with that string. Plus, the docs also use `[Deprecated]` so I'm not sure if that page just has a typo.

**Comment by dblanchette** [comment]
I decided to fix the tool to behave like the docs instead of changing the doc. Released in version 0.41.1

**Comment by GlenNicholls** [comment]
@dblanchette For clarity, does it just search for the string `[Deprecated` or `[Deprecated]`?

**Comment by dblanchette** [comment]
It searches for `[Deprecated`. It's because you can have `[Deprecated]` or, for example, `[Deprecated - use other_property]`
