### ISSUE TITLE
Spurious ellipsis in YAML examples

### ISSUE THREAD

**Issue by sim642** [coveooss/json-schema-for-humans#149]
If the schema contains examples like
```json
"examples": [
  "C",
  "Java"
]
```
and they're rendered as YAML (`examples_as_yaml: true`), then the resulting JS output displays them as

> Examples:
> ```
> C
> ...
> ```
> ```
> Java
> ...
> ```

The ellipses (`...`) at the end of each example are spurious and confusing.

**Comment by dblanchette** [comment]
Fixed in v0.41.8.

Thanks for the report!
