### ISSUE TITLE
JSON Schema implementations page

### ISSUE THREAD

**Issue by gregsdennis** [coveooss/json-schema-for-humans#154]
Hello!  Would you like to be on the [JSON Schema implementations page](https://json-schema.org/implementations.html)?  This seems like a neat tool to have listed there!

Feel free to create a PR if you want to be added ([example](https://github.com/json-schema-org/json-schema-org.github.io/pull/460)).

**Comment by dblanchette** [comment]
Hi!

I see json-schema-for-humans [is already listed](https://github.com/json-schema-org/json-schema-org.github.io/blob/d4659c140c5daa29fcf2cfdeeeb6b64980bfb110/implementations.md?plain=1#L318).

Thanks anyway, it is appreciated!
