### ISSUE TITLE
MarkupSafe is a transitive dependency

### ISSUE THREAD

**Issue by fpgmaas** [coveooss/json-schema-for-humans#157]
I applied [deptry](https://fpgmaas.github.io/deptry/) to this repository, and it found one dependency issue:

```
-----------------------------------------------------

There are transitive dependencies that should be explicitly defined as dependencies in pyproject.toml:

        MarkupSafe

They are currently imported but not specified directly as your project's dependencies.

-----------------------------------------------------
```

`Markup` from `markupsafe` is imported, but it's not a direct dependency of the project. It's a dependency of `Jinja2`. It would be a good idea to explicitly add `MarkUpSafe` to the list of project dependencies.

Disclaimer: I am the author of `deptry`, so I'm applying it to this project as a good opportunity for me to learn from and get feedback

**Comment by dblanchette** [comment]
Fixed by merging #158
