### ISSUE TITLE
Incorrect display of the "additionalProperties" flag of a referenced schema

### ISSUE THREAD

**Issue by pspot2** [coveooss/json-schema-for-humans#172]
Consider the following two schemas (`schema_test1.json` references `schema_test2.json`):

<details>
<summary>schema_test1.json</summary>

```
{
    "$id": "file:///home/eub-user/schema_test1.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "root",
    "description": "Root-level schema",
    "type": "object",
    "required": [
        "test_property01",
        "test_property02"
    ],
    "additionalProperties": false,
    "properties": {
        "test_property01": {
            "description": "Test property 01",
            "type": "string",
            "pattern": "^[a-z]{2,}[-_a-z0-9]+$"
        },
        "test_property02": {
            "$ref": "schema_test2.json"
        }
    }
}
```

</details>

<details>
<summary>schema_test2.json</summary>

```
{
    "$id": "schema_test2.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Schema test 2",
    "description": "Test 2",
    "type": "object",
    "required": [
        "other_property_3"
    ],
    "additionalProperties": false,
    "properties": {
        "other_property_3": {
            "description": "Test other property 3",
            "type": "string"
        }
    }
}
```

</details>

The first schema defines two properties: `test_property01` and `test_property02`. The second property is an object that is defined in the second schema which is referenced from the first schema. Both objects (the root one in the first schema as well as `test_property02` in the second schema) have `additionalProperties` set to `false`.

**Expectation**: for both objects in the rendered document the value of "Additional properties" is displayed as a "Not allowed" badge.

**Actual result**: for the second object the value of "Additional properties" is incorrectly displayed as "Any type | allowed" badge although it is clearly set to `false` in the respective schema.

<details>
<summary>Click to expand</summary>

# root

- [![Required](https://img.shields.io/badge/Required-blue) Property `root > test_property01`](#test_property01)
- [![Required](https://img.shields.io/badge/Required-blue) Property `root > test_property02`](#test_property02)
  - [![Required](https://img.shields.io/badge/Required-blue) Property `root > test_property02 > other_property_3`](#test_property02_other_property_3)

**Title:** root

|                           |                                                                                                          |
| ------------------------- | -------------------------------------------------------------------------------------------------------- |
| **Type**                  | `object`                                                                                                 |
| **Additional properties** | [![Not allowed](https://img.shields.io/badge/Not%20allowed-red)](# "Additional Properties not allowed.") |

**Description:** Root-level schema

| Property                               | Pattern | Type   | Deprecated | Definition           | Title/Description |
| -------------------------------------- | ------- | ------ | ---------- | -------------------- | ----------------- |
| + [test_property01](#test_property01 ) | No      | string | No         | -                    | Test property 01  |
| + [test_property02](#test_property02 ) | No      | object | No         | In schema_test2.json | Test Y            |

## <a name="test_property01"></a>![Required](https://img.shields.io/badge/Required-blue) Property `root > test_property01`

|          |          |
| -------- | -------- |
| **Type** | `string` |

**Description:** Test property 01

| Restrictions                      |                                                                                                             |
| --------------------------------- | ----------------------------------------------------------------------------------------------------------- |
| **Must match regular expression** | ```^[a-z]{2,}[-_a-z0-9]+$``` [Test](https://regex101.com/?regex=%5E%5Ba-z%5D%7B2%2C%7D%5B-_a-z0-9%5D%2B%24) |

## <a name="test_property02"></a>![Required](https://img.shields.io/badge/Required-blue) Property `root > test_property02`

|                           |                                                                                                                                   |
| ------------------------- | --------------------------------------------------------------------------------------------------------------------------------- |
| **Type**                  | `object`                                                                                                                          |
| **Additional properties** | [![Any type: allowed](https://img.shields.io/badge/Any%20type-allowed-green)](# "Additional Properties of any type are allowed.") |
| **Defined in**            | schema_test2.json                                                                                                                 |

**Description:** Test Y

| Property                                                 | Pattern | Type   | Deprecated | Definition | Title/Description     |
| -------------------------------------------------------- | ------- | ------ | ---------- | ---------- | --------------------- |
| + [other_property_3](#test_property02_other_property_3 ) | No      | string | No         | -          | Test other property 3 |

### <a name="test_property02_other_property_3"></a>![Required](https://img.shields.io/badge/Required-blue) Property `root > test_property02 > other_property_3`

|          |          |
| -------- | -------- |
| **Type** | `string` |

**Description:** Test other property 3

----------------------------------------------------------------------------------------------------------------------------
Generated using [json-schema-for-humans](https://github.com/coveooss/json-schema-for-humans) on 2022-10-27 at 22:10:02 +0000

</details>

**Comment by chrono** [comment]
I think this is a bug with the markdown renderer. I'm just encountering this after switching renderers.

**Comment by chrono** [comment]
This also manifests in the fixtures:
https://github.com/coveooss/json-schema-for-humans/blob/9ced1e2a71eea858e1b9c49273828dfc2ffebeaf/docs/examples/examples_flat_default/references.html#L108-L136

vs

https://github.com/coveooss/json-schema-for-humans/blob/9ced1e2a71eea858e1b9c49273828dfc2ffebeaf/docs/examples/examples_md_default/references.md?plain=1#L67-L73
