### ISSUE TITLE
Can the pytz dependency be loosened?

### ISSUE THREAD

**Issue by rob-b** [coveooss/json-schema-for-humans#180]
Currently it's set to `pytz = "^2021.1"` and so blocks upgrading pytz to any 2002.x versions

https://github.com/coveooss/json-schema-for-humans/blob/95de4fe4aecea6a076c674e4230d8b727a5b1546/pyproject.toml#L33

This means that recent[ changes to timezone info](https://data.iana.org/time-zones/tzdb/NEWS) for countries such as Palestine, Ukraine and Mexico is missing

**Comment by dblanchette** [comment]
Sure! Change released in v0.44.1
