### ISSUE TITLE
required properties are not shown correctly if properties has a property with name required. 

### ISSUE THREAD

**Issue by Anuj-Kaushal** [coveooss/json-schema-for-humans#182]
When we have a property named "required" then the required jsonschema construct is not correctly interpreted.

"properties": {
           "name": {
             "$ref": "commons_v01.json#/definitions/nameString"
           },
           "required": {
             "$ref": "commons_v01.json#/definitions/displayNameString"
           },
           "age": {
             "$ref": "commons_v01.json#/definitions/nameString"
           }
}, 
"required": [
           "name",
           "age"
         ], 
         
       -------- 
  
  In this case, I would expected the generated documentation to show name, age as required however none of the properties is shown as required because the properties has one of the property names as "required".

**Comment by dblanchette** [comment]
Thanks for the report. It seems the logic to check if something is a property had a flaw.

Should be fixed in version 0.44.2 released just now.

**Comment by Anuj-Kaushal** [comment]
Thanks for the fix. Will try it out and let you know.
