### ISSUE TITLE
nit: type annotation is wrong for GenerationConfiguration.template_path

### ISSUE THREAD

**Issue by vdwees** [coveooss/json-schema-for-humans#188]
It might be intentional, but looks like it returns  `Path`, not `Optional[Path]`

https://github.com/coveooss/json-schema-for-humans/blob/f73d7646e995d98f857ddad60be9391fad0225f1/json_schema_for_humans/generation_configuration.py#L98-L108

**Comment by dblanchette** [comment]
The lib used typing loosely, I just fixed that by adding checks with mypy and fixed this issue and many many other.

Thanks!
