### ISSUE TITLE
Period (.) in property name causes unresponsive expandable properties 

### ISSUE THREAD

**Issue by mbkranz** [coveooss/json-schema-for-humans#202]
If you have a period (eg `constraints.maxLength`) as a property name, one cannot expand the property.

**Comment by mbkranz** [comment]
This appears to be due to the html ids. Are there any issues with adding a period in re.sub [here](https://github.com/coveooss/json-schema-for-humans/blob/893424b0cfbf5f6b66ca5558ef7bc2bf2563808e/json_schema_for_humans/schema/intermediate_representation.py#L42)?

`escaped = re.sub("[^0-9a-zA-Z_-]", "_", str(html_id))` to
`escaped = re.sub("[^0-9a-zA-Z_-]|\.", "_", str(html_id))`

**Comment by mbkranz** [comment]
^ Looks like may be best to add to list (see above #203 PR)

**Comment by dblanchette** [comment]
Fixed by PR #203
