### ISSUE TITLE
When generating HTML enable users to suppress date/time output in the <footer> section of the generated document.

### ISSUE THREAD

**Issue by wsberry** [coveooss/json-schema-for-humans#235]
The reason for this is to prevent 'git' from assuming a change has taken place in the HTML contents when only the date/time as been updated.

I.e.,
<p class=generated-by-footer>Generated using <a href=https://github.com/coveooss/json-schema-for-humans>json-schema-for-humans</a> on 2024-03-06 at 12:09:57 -0500</p> </footer></body></html>

'on 2024-03-06 at 12:09:57 -0500' causes a change in the document contents and therefore the document to be flagged by git as being updated.

My desire is to only have changes related to HTML content I am concerned with to be flagged by git (i.e., things that are unrelated to the date/time).

**Comment by stephenberry** [comment]
Having the time stamp prevents the ability to auto generate the html and commit to a repository. Simply having an option to prevent the timestamp allows the html schema to be tracked over time and auto generated and saved in a repository.

**Comment by stephenberry** [comment]
Sweet, thanks!
