### ISSUE TITLE
Support for "if", "then", and "else" keywords (conditional subschemas)

### ISSUE THREAD

**Issue by dblanchette** [coveooss/json-schema-for-humans#27]
Doc here: https://json-schema.org/understanding-json-schema/reference/conditionals.html

This could be supported easily by making a tabbed section with the if, then, and else sections as 3 tabs.

**Comment by mauvilsa** [comment]
@dblanchette I have tested https://github.com/coveooss/json-schema-for-humans/pull/28 using the schema https://github.com/omni-us/narchi/blob/master/schema/narchi_schema.json and from what I have seen all looks good.
