### ISSUE TITLE
string pattern interpreted as html tags

### ISSUE THREAD

**Issue by mauvilsa** [coveooss/json-schema-for-humans#29]
In some cases parts of string pattern get interpreted as html tags which results in not correctly displaying the original pattern. An example of this is the following:
```json
{
  "type": "string",
  "pattern": "^(<<variable:([-+/*0-9A-Za-z_]+)>>|<<auto>>)$"
}
```

The generated html displays it as
![Screenshot from 2020-05-21 19-01-48](https://user-images.githubusercontent.com/5780272/82585018-9f1afd80-9b95-11ea-91a0-fddbac9a4088.png)
which is due `<variable...` and `<auto>` becoming html tags
```html
<code>^(&lt;<variable:([-+ *0-9a-za-z_]+)="">&gt;|&lt;<auto>&gt;)$</auto></variable:([-+></code>
```

**Comment by dblanchette** [comment]
Dumb oversight on my part. Fix released in version 0.11.1
