### ISSUE TITLE
Recursive element details location

### ISSUE THREAD

**Issue by mauvilsa** [coveooss/json-schema-for-humans#30]
Regarding the new support for recursive definitions (https://github.com/coveooss/json-schema-for-humans/issues/8) I have a proposal that I think could make things slightly more understandable. Currently the details of a recursive element are shown the first time it appears, and all others are links to this first instance. However, the first time a recursive element appears could be deeply nested. It could be better instead to show the details of the recursive element the first time it appears in the least depth.

An example is the following
![Screenshot from 2020-05-21 19-25-31](https://user-images.githubusercontent.com/5780272/82587130-e951ae00-9b98-11ea-850f-c6935ab63383.png)
The graph in the first level links to a definition which is deeply nested. Someone trying to understand this schema would first like to learn about the elements at the first level, so having this link to a deeper level just makes it a bit more confusing than what it would be if the details were at this first level.

**Comment by dblanchette** [comment]
I agree and I also don't necessarily like the names used in the link (`blocks_array_items__graph` is not really a description "for humans").

I'll look into solutions in the next iterations.

**Comment by dblanchette** [comment]
@mauvilsa Fix released in version 0.13.0. I tested with the schema you sent in issue #8 and `graph` is now documented at the top level.

Let me know if you have more ideas, I'm always open to a new challenge :)
