### ISSUE TITLE
Support YAML as source files

### ISSUE THREAD

**Issue by dblanchette** [coveooss/json-schema-for-humans#33]
Looking at #32 , it seems some people are using yaml instead of JSON for their schemas.

Since YAML is a superset of JSON, loading using PyYaml all the time would allow this without impacting JSON versions.

**Comment by TSheahan** [comment]
Confirmed, I've been loading YAML via PyYaml then calling generate_from_schema() on the resulting collection.

This looks like a sensible enhancement for command line users.

**Comment by dblanchette** [comment]
Thanks for the confirmation :)

Released in version 0.12.0
