### ISSUE TITLE
Complex regex structures in patternProperties lead to duplicate html IDs

### ISSUE THREAD

**Issue by da1910** [coveooss/json-schema-for-humans#41]
Complex schema with pattern properties are likely to have duplicate html IDs since many regex tokens are replaced with underscores. This causes the generated documentation to be unusable in these cases.

I would suggest that using the pattern is not the best solution to this issue, we render the heading with the title, this would be a more sensible choice. Or indeed to use the parent element's name and an enumerator. Either way this is a regression to 0.9.0 as far as I can tell.

**Comment by dblanchette** [comment]
@da1910 I went with the enumerator option since there is not always a title associated. Let me know what you think and I will merge and release.

Have a nice day!

**Comment by da1910** [comment]
Looks good to me, handles the use-case I have very nicely!

**Comment by dblanchette** [comment]
Fix released in version 0.15.0.
