### ISSUE TITLE
YAML does not support tabs for indentation

### ISSUE THREAD

**Issue by da1910** [coveooss/json-schema-for-humans#45]
YAML spec explicitly rules out the use of tabs for indentation, while most JSON parsers will just ignore whitespace.
I would expect the latter behaviour, but because we use YAML as the parser this is not the current behavior.

As two options:
1. We could strip the whitespace out, either ourselves or using a package like JSONminify.
2. We could explicitly replace tabs with spaces.

Id be happy to take this and make a PR if you have an option you prefer.

**Comment by dblanchette** [comment]
How about using `json.load` when the extension of the provided schema file is .json and using `yaml.safe_load` in other cases?

Barring this, I prefer option 2.

Thanks for the report and let me know if you start working on a PR :)

**Comment by dblanchette** [comment]
Released in version 0.15.1
