### ISSUE TITLE
--no-link-to-reused-ref does not work

### ISSUE THREAD

**Issue by cakrt** [coveooss/json-schema-for-humans#49]
Hi, it seems that --no-link-to-reused-ref does not work - I still see the "Same definition as" links even though I enabled this.

I am using python 3.7.8 on Windows 10.

**Comment by dblanchette** [comment]
HI @cakrt, I broke that option in a refactor for version v0.13.0, sorry about this.

It should now work properly with version 0.15.3.

Don't hesitate to reopen this issue if it does not.

**Comment by cakrt** [comment]
Perfect. It works as expected. Thanks a lot!
