### ISSUE TITLE
Examples section spacing issue

### ISSUE THREAD

**Issue by AdrianGjerstad** [coveooss/json-schema-for-humans#65]
There is a problem when generating elements with examples. The issue has to do with the fact that Bootstrap automatically adds a `1rem` margin below any `pre` HTML tags. This results in example blocks appearing as though they have another line after the end.

The fix I have found is to add a class to the `pre` tags containing the examples that says `m-0` or `mb-0`. This will override Bootstrap's default behavior and remove the spacing. I was going to open a PR myself, but couldn't find where to place this code. Any help is greatly appreciated.

**Comment by dblanchette** [comment]
Hi @AdrianGjerstad and sorry for the delay!

I deployed a fix in version 0.27.1. I added an override in the custom CSS that sets the margin to 0 for `pre` inside `.examples`.

Have a nice day!
