### ISSUE TITLE
Consider adding "break-on-newline" to markdown2 options or make configurable

### ISSUE THREAD

**Issue by sw23** [coveooss/json-schema-for-humans#68]
We have a few schemas that contain "\n" characters in their descriptions for better formatting, so we've found it useful to pass the "break-on-newline" extra to the markdown2 call, such that <br> tags are used to preserve the newlines.

Is this something that'd be good to make a config option?  Alternatively the config file could support passing any of the options, however I'm not sure many others are useful in this context:
https://github.com/trentm/python-markdown2/wiki/Extras

**Comment by dblanchette** [comment]
This should probably be the default. In our own usage here at Coveo, we put `<br/>` directly in the templates, but just using a new line would be better.

I'll add the option soon!

**Comment by dblanchette** [comment]
Released in version 0.28.

**Comment by dblanchette** [comment]
Released in version 0.29.0, someone else made a PR to make all options configurable, which is better.

**Comment by sw23** [comment]
Thank you very much!!
