### ISSUE TITLE
Multiline code examples are rendered in single line 

### ISSUE THREAD

**Issue by sureshkmit** [coveooss/json-schema-for-humans#77]
### **Expected:**
<img width="1137" alt="Screen Shot 2021-02-18 at 7 44 32 PM" src="https://user-images.githubusercontent.com/429665/108369583-c0db0b00-7221-11eb-9193-8fa57f45140e.png">

### **Actual:**
<img width="1137" alt="Screen Shot 2021-02-18 at 7 41 46 PM" src="https://user-images.githubusercontent.com/429665/108369633-ccc6cd00-7221-11eb-9bd3-0cdb9a219824.png">

**Comment by dblanchette** [comment]
Hi @sureshkmit, thanks for the report. Could you share your schema or a relevant section of it that reproduces the issue?

Also, the options you are using (and version if not the latest).

I think this might be related to one of the rendering option.

Thanks

**Comment by dblanchette** [comment]
Closing this as stale. Don't hesitate to open a new issue if you have steps to reproduce.

I think this is caused by not setting `break-on-newline` in the options https://coveooss.github.io/json-schema-for-humans/examples/examples_js_default/Configuration.html#markdown_options
