### ISSUE TITLE
Passing file path to template as template_name

### ISSUE THREAD

**Issue by azaroth42** [coveooss/json-schema-for-humans#78]
Thank you for such a great tool!

Question: I am currently abusing the fact that `os.path.join()` will reset if given an absolute path to join, and hence line 1259 where generate calculates the `template_folder` can be tricked into reading from any arbitrary directory. 

For example:
> $ generate-schema-doc --config no_show_breadcrumbs --config description_is_markdown --config template_name=$PWD/template schema/object.json html/object.html

reads its template from the current directory/template rather than "js" or "flat".

Is this intentional, and can be relied on to not go away (and if so, could it be documented please?) or is this a not-so-clever hack and I should do something more sane? :)

**Comment by dblanchette** [comment]
Hi! Thanks for the good words.

I can say that this was not intended. However, it would be great to have a CLI option to pass a folder for a custom template in a config file/on the CLI.

I might add an option soon or you can submit a PR to make the behaviour official :)

It's nice to see people using this library, especially in unexpected ways!

Also, if you have an interesting template to submit, feel free to open a PR!

**Comment by azaroth42** [comment]
Minimal PR for the changes above. Tests are all green.

The template changes are minimal and also not at all clever. It just pulls in the `title` of a node to sit alongside the name of the property. Then I use the title slot to record the equivalent ontological form. We use [JSON-LD](https://www.w3.org/TR/json-ld11/) to make sure our data is usable as JSON and useful in a broader context.

Temporary, half-finished example: https://linked-data.yalespace.org/docs/model/object.html
