### ISSUE TITLE
Same definition as link is inside code block

### ISSUE THREAD

**Issue by calebhalvy** [coveooss/json-schema-for-humans#85]
Currently, in the type info table in the markdown template, definition links are being rendered as code instead of links:

![image](https://user-images.githubusercontent.com/3345329/116131287-d04b5a00-a691-11eb-8f69-0d24d37bf126.png)
https://github.com/coveooss/json-schema-for-humans/blob/master/docs/examples/examples_md_with_badges/recursive_parent_in_definition.md

**Comment by dblanchette** [comment]
Fixed in #89
