### ISSUE TITLE
Error Artifact in Generated Docs

### ISSUE THREAD

**Issue by KiNgMaR** [coveooss/json-schema-for-humans#90]
First, thanks a lot for maintaining this!

Now, the question. The following input produces an HTML document that seems to contain an error artifact ("0x7f233bf07ee0"):

![image](https://user-images.githubusercontent.com/438358/117111881-87c62780-ad88-11eb-88b6-cf6dc67ca27a.png)

```
{
    "type": "object",
    "properties": {
        "uniqueId": {
            "type": "string",
            "description": "Unique ID in source/master system",
            "maxLength": 255
        }
    }
}
```

The command used to generate is:

```
docker build --iidfile=/tmp/schemas.docker .

docker run \
        -v $PWD:/code \
        -w /code \
        --rm \
        `cat /tmp/schemas.docker` \
        generate-schema-doc \
            --config description_is_markdown=false \
            --config expand_buttons=true \
            "test.json"
```

And the environment is a fresh Docker container:

```
FROM python:3-buster

RUN pip install json-schema-for-humans
```

Any hints on how to get the full error message and/or how to fix it? :)

**Comment by dblanchette** [comment]
Hi @KiNgMaR !

Version 0.33.1 that was just released should address the issue.
