### ISSUE TITLE
Name tabbed sections after a property of an object

### ISSUE THREAD

**Issue by GuittonHubert** [coveooss/json-schema-for-humans#91]
First of all, many thanks for this great tool!

I have the following schema and would like to use the properties.name.const value as the displayed name of the tabs, i.e. "name 1", "name 2", etc.:
```
{
	"oneOf": [{
		"type": "object",
		"properties": {
			"name": {
				"const": "name 1"
			},
			"value": {}
		}
	}, {
		"type": "object",
		"properties": {
			"name": {
				"const": "name 1"
			},
			"value": {}
		}
	}]
}
```
I changed every object to a reference, with the last part of it matching properties.name.const value, but I cannot use reference since the schema is then too complex. I tried to modify the intermediate representation and the SchemaNode along with the tabbed section template unsuccessfully. Please, could you tell me if there is a way to do it, or what should I modify in the code to do it?

Thank you very much for your support.

**Comment by dblanchette** [comment]
Hi! 

Glad that you enjoy the tool :)

You can add a title to the tabs like this:
```json
{
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "name": {
          "const": "name 1"
        },
        "value": {}
      },
      "title": "Title for tab 1"
    },
    {
      "type": "object",
      "properties": {
        "name": {
          "const": "name 1"
        },
        "value": {}
      },
      "title": "Title for tab 2"
    }
  ]
}
```

You should get something like that:
![chrome_P4jy9kLKRA](https://user-images.githubusercontent.com/5759247/119531679-2b847100-bd52-11eb-8d6c-0a872fe6576b.png)

**Comment by GuittonHubert** [comment]
Thank you very much for your answer; I tested it successfully! I was not aware that this possibility already existed in your piece of S/W and this is very handy for my use case. Once again thank you for your great tool!

**Comment by dblanchette** [comment]
Glad that it worked, have a nice day :)
