### ISSUE TITLE
Wrong specific value for constant tuples

### ISSUE THREAD

**Issue by moulinfr** [coveooss/json-schema-for-humans#94]
Hello,

I have the following valid JSON schema:
```
{
"type": "array", 
"oneOf": [
    { "title": "1st constant", "const": [ 1, 2 ] },
    { "title": "2nd constant", "const": [ 3, 4 ] }
]
}
```
I am expecting to have an HTML page with "One Of" and two tabs: "1st constant" and "2nd constant", plus:

- 1st tab:
```
Type: const
Specific value: [ 1, 2 ]
```
- 2nd tab:
```
Type: const
Specific value: [ 3, 4 ]
```
But instead, "Specific value" is always set to "null". 

Your help would be greatly appreciated. Thanks.

**Comment by dblanchette** [comment]
Hi @moulinfr ,

Thanks for bringing the issue to my attention. The code was not handling correctly having a `const` value not being a simple int, str or bool.

Fixed in version 0.34.1 that just released to pypi.

Have a nice day!
